apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
spec:
   selector:
     matchLabels:
        app: mongodb
   replicas: 1
   template: #template of the pods(better called pods than template)
     metadata:
        #you don't need a name for the pod here     
        labels:
          app: mongodb
     spec:
        containers:  
        - name: mongodb #changing the name doesn't change anything because it's something internel  
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        volumes:
          - name: mongo-persistent-storage        
            persistentVolumeClaim:
              claimName: mongo-pvc


---

apiVersion: v1
kind: Service
metadata:
   name: fleetman-mongodb

spec:
  selector:
    app: mongodb

  ports:
    - name: mongoport
      port: 27017
    

  type: ClusterIP  